### ISSUE TITLE
README

### ISSUE THREAD

**Issue by Helveg** [ebrains-cls-interactive/usecases-info#12]
Could a README be added with instructions to add a section to the JSON and the possible values of the fields?

**Comment by stefanoantonel** [comment]
Indeed I have added some information of how to add use cases in the readme page.
https://github.com/ebrains-cls-interactive/usecases-info#how-to-add-new-use-case
That points to the documentation https://github.com/ebrains-cls-interactive/usecases-info/blob/develop/documentation/add_new_usecase.md

**Comment by Helveg** [comment]
Thanks! There's a little formatting error in the Markdown though, 1 link has inverted `[label](href)` to `(label)[href]`
